from shared.event_log import (
    EVENT_LOG_COLUMNS,
    EVENT_LOG_PATH,
    append_cash_adjusted_event,
    append_event,
    append_equity_snapshot_recorded_event,
    append_exit_decision_generated_event,
    append_fill_processed_event,
    append_position_closed_event,
    append_position_opened_event,
    append_run_lifecycle_event,
    append_state_change_event,
    append_validation_event,
    ensure_event_log_exists,
)
